server:
  port: 8090
  
spring:  h2:    console:      enabled: true
      path: /h2-console  datasource:    generate-unique-name: false  jpa:    properties:      javax:
        persistence:
          validation:
            mode: none  data:    web:      pageable:        default-page-size: 10
        max-page-size: 100